### ISSUE TITLE
Start at  _page = 1

### ISSUE THREAD

**Issue by stemuk** [fablue/building-a-social-network-with-flutter#2]
Hey,
It's not technically an issue, I just wanted to say thank you for the awesome tutorial! :+1: 

I have one question however: What changes to the Step 1 final code do I have to make in order to start the page view at `_page = 1`, i.e start at the "feed" view? The current version of the code allows you to set `_page = 1`, which however leads to the bug that you can't scroll left, to `_page = 0` anymore.

Maybe `onPageChanged` has to be implemented differently in order to accomplish that?

**Comment by fablue** [comment]
That shouldn't be a problem! You have to pass the initalPage param to the [PageController](https://docs.flutter.io/flutter/widgets/PageController-class.html). 

It should look something like this:

```dart
  @override
  void initState() {
    super.initState();
    pageController = new PageController(initialPage: this._page);
  }
```

then just change the initial _page variable to the page you want ☺️
