### ISSUE TITLE
Initialization of variables

### ISSUE THREAD

**Issue by tenhobi** [fablue/building-a-social-network-with-flutter#4]
Hi, I am new to Flutter, but is there any reason why to initialize `PageController` in `initState` method instead initialize it right in the declaration?

```dart
class _MainPageState extends State<MainPage> {
...
  // why not this way?
  PageController _pageController = new PageController(); 
...
  // why this way
  @override
  void initState() {
    super.initState();
    _pageController = new PageController();
  }
...
}
```

**Comment by fablue** [comment]
I think you could do this in this particular case ☺️ 
Have a look into the doc: 
https://docs.flutter.io/flutter/widgets/State/initState.html

Both solutions should work fine! 👍

**Comment by fablue** [comment]
Should I bring the initialization out, to avoid confusion?

**Comment by tenhobi** [comment]
OK, so it's the same. I thought so.

According to https://www.dartlang.org/guides/language/effective-dart/usage#do-initialize-fields-at-their-declaration-when-possible it would be nicer to initialize it at it's declaration. :-)

**Comment by fablue** [comment]
Good Idea! 👍 
Thank you ☺️
